### ISSUE TITLE
Flac problems, update to 3.0.18-02

### ISSUE THREAD

**Issue by firefoxlover** [flathub/org.videolan.VLC#172]
There is a small bugfix that was added somewhere. Its just a fix for extreme stutters, making FLACs unplayable.

This issue does not exist on the latest nightly, but this would be too extreme for this package.

The fix 3.0.18-2, in debian backported to x-1 solved this problem. I dont know where to get this version, but maybe thats easy to change?

**Comment by nurupo** [comment]
Related links:

- https://salsa.debian.org/multimedia-team/vlc/-/commit/c5289e84e17421c1e40ef9f0953b6c0f96a20cb2
- https://code.videolan.org/videolan/vlc/-/commit/c2dd4bfefe079e49db1789eb76be3885e4fc31b4

**Comment by nurupo** [comment]
FYI you are requesting this to be fixed in the wrong place. If something as core as flac playback is broken, VLC devs should just release a new patch version with the issue fixed, i.e. VLC 3.0.19, instead of fixing it in the trunk and letting it sit there for over 9 months, with users suffering the issue, having distros to manually apply the patch, not to mention Windows users who don't get the patch at all. So what you should really have done is open an issue in VideoLAN's issue tracker asking them to release 3.0.19, which then everyone, including Flathub, would pick up. Having Debian Unstable, Flathub, etc. manually apply the patch is a bit backwards.

**Comment by nurupo** [comment]
Here we go, just a little respectful nudge asking them to release 3.0.19 https://code.videolan.org/videolan/vlc/-/issues/27477#note_408971, hopefully they don't misinterpret it and take it the wrong way.

I actually didn't see this VideoLAN issue discussion before - it seems like they are not just letting the fix sit in the trunk, they have been wanting to accelerate the 3.0.19 release for some time now exactly due to this bug, which I'm glad to learn.
